# Generated by Django 5.2.6 on 2025-11-11 15:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_paciente_usuario_alter_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Fim do atendimento'),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Início do atendimento'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agendamento.especialidade'),
            preserve_default=False,
        ),
    ]
