# Generated by Django 5.2.6 on 2025-11-13 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_remove_medico_atualizado_em_remove_medico_criado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-data_hora']},
        ),
        migrations.AlterModelOptions(
            name='especialidade',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='agendamento.medico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='agendamento.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exame',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='agendamento.prontuario'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='agendamento.especialidade'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='agendamento.paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('medico', 'data_hora')},
        ),
    ]
