# Generated by Django 5.2.6 on 2025-11-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0010_alter_consulta_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
