# Generated by Django 5.2.6 on 2025-11-16 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0011_alter_prontuario_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='cid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='diagnostico',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuario',
            name='medicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='queixa',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
