# Generated by Django 5.2.6 on 2025-11-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0012_prontuario_cid_prontuario_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos_prontuario/'),
        ),
    ]
