# Generated by Django 5.2.6 on 2025-11-26 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0015_paciente_foto_paciente_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='conduta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='evolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='exame_fisico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='frequencia_cardiaca',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='frequencia_respiratoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='pressao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='saturacao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='temperatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='prontuarios/anexos/'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='queixa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
